// 一天的毫秒数
export const ONE_DAY_MILLION_SECONDS = 3600 * 1000 * 24

// 一周的毫秒数
export const ONE_WEEK_MILLION_SECONDS = ONE_DAY_MILLION_SECONDS * 7

// 30天的毫秒数
export const THIRTY_DAYS_MILLION_SECONDS = ONE_DAY_MILLION_SECONDS * 30
